grafana:
  build: ./grafana/
  ports:
    - "80:80"
    - "3000:3000"
  links:
    - influxdb
influxdb:
  build: ./influxdb/0.9/
  ports:
    - "8086:8086"
    - "8083:8083"
  expose:
    - "8090"
    - "8099"

